[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Remove .html from URLs
[[redirects]]
  from = "/*"
  to = "/:splat.html"
  status = 200
  force = false